---
    
apiVersion: v1
kind: Service
metadata:
  name: reviews-v1
spec:
  selector:
    app: reviews
    version: v1
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080

---

apiVersion: v1
kind: Service
metadata:
  name: reviews-v2
spec:
  selector:
    app: reviews
    version: v2
  ports:
  - protocol: TCP
    port: 9080
    targetPort: 9080